"""Final entry

Revision ID: ac1b570b4f85
Revises: 95d6128f87bd
Create Date: 2025-06-14 18:58:15.228206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1b570b4f85'
down_revision: Union[str, None] = '95d6128f87bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'update_at')
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'updated_at')
    # ### end Alembic commands ###
